files.orders.directory=Orders
files.orders.file-name-base=Orders_
files.orders.file-extension=.txt
files.products.file-name=Data/Products.txt
files.taxes.file-name=Data/Taxes.txt
files.exports.file-name=Backup/DataExport.txt